[options]
library = "Vte"
version = "2.91"
deprecate_by_min_version = true
generate_safety_asserts = false
min_cfg_version = "1.0"
single_version_file = true
target_path = "."
work_mode = "normal"
generate_builder = true

girs_directories = [
    "../gir-files/",
    "../vte/share/gir-1.0/",
]

external_libraries = [
    "Atk",
    "Cairo",
    "GLib",
    "Gdk",
    "GdkPixbuf",
    "Gio",
    "Gtk",
    "Pango",
]

generate = [
    "Vte.Align",
    "Vte.CursorBlinkMode",
    "Vte.CursorShape",
    "Vte.EraseBinding",
    "Vte.EventContext",
    "Vte.FeatureFlags",
    "Vte.Format",
    "Vte.ProgressHint",
    "Vte.PropertiesRegistry",
    "Vte.PropertyFlags",
    "Vte.PropertyId",
    "Vte.PropertyType",
    "Vte.Pty",
    "Vte.PtyError",
    "Vte.PtyFlags",
    "Vte.Regex",
    "Vte.RegexError",
    "Vte.SelectionFunc",
    "Vte.SystemdContextExitCondition",
    "Vte.SystemdContextOperation",
    "Vte.SystemdContextType",
    "Vte.SystemdPropertyId",
    "Vte.Terminal",
    "Vte.TerminalSpawnAsyncCallback",
    "Vte.TextBlinkMode",
    "Vte.Uuid",
    "Vte.UuidFormat",
    "Vte.WriteFlags",
    "Vte.Properties",
]

manual = [
    "Atk.ImplementorIface",
    "GLib.Bytes",
    "GLib.DestroyNotify",
    "GLib.Error",
    "GLib.Pid",
    "GLib.SpawnChildSetupFunc",
    "GLib.SpawnError",
    "GLib.SpawnFlags",
    "GLib.Uri",
    "GLib.Variant",
    "GObject.InitiallyUnowned",
    "GObject.Value",
    "Gdk.Cursor",
    "Gdk.CursorType",
    "Gdk.Event",
    "Gdk.RGBA",
    "GdkPixbuf.Pixbuf",
    "Gio.AsyncReadyCallback",
    "Gio.AsyncResult",
    "Gio.Cancellable",
    "Gio.Initable",
    "Gio.MenuModel",
    "Gio.OutputStream",
    "Gtk.Buildable",
    "Gtk.Scrollable",
    "Gtk.Widget",
    "Gtk.Window",
    "Pango.FontDescription",
    "cairo.FontOptions",
    "cairo.Surface",
]
